CakePHP課題１実装
yuinakoizumi/quelcode-cakephp pull request #2
Opened 2020-11-05 06:11 UTC by Yuina1012

CakePHP課題１実装を行いまいた。レビューよろしくお願いします。

2020-11-05 07:38 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/UsersController.php
> +        if($user['role' == 'user']){
認証回りで恐ろしいタイポをしているので見直してください

2020-11-05 08:58 UTC, Yuzunoha commented
![image](https://user-images.githubusercontent.com/22877094/98219475-64185500-1f90-11eb-918a-622a1696e181.png)

2020-11-05 09:04 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			$this->Biditems->save($biditem);
リクエストで送られたデータをsaveしたら失敗する可能性が十分にあるので、
if文を使いましょう

```php
if ($this->Biditems->save($biditem)) {
    /* saveが成功したときの処理 */
} else {
    /* saveが失敗したときの処理 */
}

```

2020-11-05 09:09 UTC, Yuzunoha commented
### 不具合
商品詳細画面がエラーになる
http://localhost:10380/auction/view/1

### コメント
直しましょう

![image](https://user-images.githubusercontent.com/22877094/98220690-04bb4480-1f92-11eb-856f-53865a37fec1.png)

2020-11-05 11:00 UTC, Yuina1012 commented
ユズノハさんレビューありがとうございます。
ご指摘いただいた箇所のエラーが出ないように修正と改善します。

2020-11-12 00:32 UTC, Yuzunoha commented
DB設計書
https://docs.google.com/spreadsheets/d/1QkWjrnO1VrAmaMafitD6Elivu2U0_zz1O52o-bSpt1c/edit?usp=sharing
詳細設計
https://docs.google.com/document/d/1owCYBChJY6jgCYUNB_tPv3l1ViE7XvT9lgsQb2sYaSQ/edit?usp=sharing

2020-11-12 00:51 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/view.ctp
> +</div>
侵入禁止マークが出ているので最終行の末尾では1回改行しましょう！

2020-11-12 00:55 UTC, Yuzunoha commented
出品された画像を保存するフォルダ
quelcode-cakephp/html/mycakeapp/webroot/img/auction/
が無いのでgitに追加しましょう。

ユーザからアップロードされた商品画像はgitで無視したいので、.gitkeepと.gitignoreを使いましょう

img/auction/ 配下の .gitkeep をgit管理して、それ以外のファイルを無視すればよいです。

よくある .gitkeepと.gitignoreの設定なのでググれば出てきます！

2020-11-12 00:59 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/add.ctp
> +<?= $this->Form->create('biditem', ['type' => 'file']) ?>
```suggestion
<?= $this->Form->create($biditem, ['type' => 'file']) ?>
```
ここ書き方が間違ってますね

2020-11-12 01:09 UTC, Yuzunoha commented on html/mycakeapp/src/Model/Table/BiditemsTable.php
> +            ->maxLength('iteminfo', 1000)
```suggestion
            ->maxLength('iteminfo', 1000, '1000文字以内で入力してください')
```
こうするとエラーメッセージを出せます

2020-11-12 01:11 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/add.ctp
> +	echo $this->Form->textarea('iteminfo');
```suggestion
	echo $this->Form->control('iteminfo', ['type' => 'textarea']);
```
controlを使った方が、エラーメッセージが出せたりするのでよいです

2020-11-12 01:12 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/add.ctp
> +	echo $this->Form->checkbox('finished');
```suggestion
```
このチェックボックス不要ですね

2020-11-12 01:15 UTC, Yuzunoha commented on html/mycakeapp/src/Model/Table/BiditemsTable.php
> +        $validator->setProvider('custom', 'App\Model\Validation\CustomValidation');
CustomValidation クラスはこのprでは使っていないので消しましょう

2020-11-12 01:15 UTC, Yuzunoha commented on html/mycakeapp/src/Model/Validation/CustomValidation.php
> +class CustomValidation extends Validation
CustomValidation クラスはこのprでは使っていないので消しましょう

2020-11-12 01:21 UTC, Yuzunoha commented on html/mycakeapp/src/Model/Table/BiditemsTable.php
> +            }, 'isCheck', [
```suggestion
            }, 'extension', [
```
ルール名がisCheckは何のチェックか分からないのでextensionにしましょう

2020-11-12 01:22 UTC, Yuzunoha commented on html/mycakeapp/src/Model/Table/BiditemsTable.php
> +                'message' => '画像の拡張子'
```suggestion
                'message' => '画像の拡張子が無効です'
```
メッセージっぽくしましょう

2020-11-12 01:26 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
>  			}
```suggestion
			// id,image_name以外を一旦保存
			if ($this->Biditems->save($biditem)) {
				// 更新
				$biditem = $this->Biditems->patchEntity($biditem, $data);
				// pathinfoで配列で拡張子取り出す
				$path_parts = pathinfo($biditem['image_name']);
				// 拡張子を変数に入れる
				$fileExt = $path_parts["extension"];
				// ファイル名を変更
				$biditem->image_name = $biditem['id'] . '.' . $fileExt;
				// もし保存できたら
				if ($this->Biditems->save($biditem)) {
					// 画像データをとってくる
					$file = $_FILES['image_name']['tmp_name'];
					// パスの指定
					$filepath = '/var/www/html/mycakeapp/webroot/img/auction/' . $biditem['id'] . '.' . $fileExt;
					// move_uploaded_fileで行先を指定
					$success = move_uploaded_file($file, $filepath);
					// 成功時のメッセージ
					$this->Flash->success(__('保存しました。'));
					// トップページ（index）に移動
					return $this->redirect(['action' => 'index']);
					// }
				}
			}
```

2020-11-12 02:46 UTC, Yuina1012 commented
ユズノハさんレビューありがとうございます！
.gitkeep, .gitnore 調べました！gitには管理についての機能が様々あるんですね。
エラーメッセージの入力しておりました。
フォームのcontrol について知識不足でなんとなく使っていたので調べます。
わかりやすい命名がコードは必要ですね、意識します！
ありがとうございます！

2020-11-12 03:09 UTC, Yuzunoha commented
メモ
画像が無視されていない

2020-11-12 03:20 UTC, Yuzunoha commented
> 出品された画像を保存するフォルダ
> quelcode-cakephp/html/mycakeapp/webroot/img/auction/
> が無いのでgitに追加しましょう。
> 
> ユーザからアップロードされた商品画像はgitで無視したいので、.gitkeepと.gitignoreを使いましょう
> 
> img/auction/ 配下の .gitkeep をgit管理して、それ以外のファイルを無視すればよいです。
> 
> よくある .gitkeepと.gitignoreの設定なのでググれば出てきます！

こちらに関して、.gitkeepを作成したのはOKです！
ユーザがアップロードした商品画像(`webroot/img/auction/6.JPG` とか)がgitから無視されていないので、無視するように.gitignoreを設定しましょう

2020-11-12 03:23 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/add.ctp
> +	echo $this->Form->control('iteminfo');
```suggestion
	echo $this->Form->control('iteminfo', ['type' => 'textarea']);
```
1,000文字入力できるフォームなのでtextareaにしましょう！

2020-11-12 04:51 UTC, Yuina1012 commented
レビューありがとうございます！
controlにするとtype指定をしないとバリデーション 効かなくなってしまうのですね

2020-11-12 06:35 UTC, Yuzunoha commented
> レビューありがとうございます！
> controlにするとtype指定をしないとバリデーション 効かなくなってしまうのですね

type指定があっても無くてもバリデーションは効きます

2020-11-12 06:44 UTC, Yuzunoha commented on .gitignore
> +!.gitignore
gitignoreの書き方が違いますね><

やりたいことは

>quelcode-cakephp/html/mycakeapp/webroot/img/auction/ 配下の .gitkeep をgit管理して、それ以外のファイルを無視する

です

gitignoreの書き方を調べてください～

2020-11-12 07:17 UTC, Yuina1012 commented on .gitignore
> +!.gitignore
ありがとうございます！もう一度調べて書き直しました！
VScode上だとwebroot/img/auctionかの.gitkeep以外グレーに薄くなっているので、無視されてると思うですがあまり自信がないです！

2020-11-12 11:34 UTC, kai-kou commented
確認しました。

### 【要修正】

- `.gitignore` の下記2行をなぜ追加されたのか教えてもらってよいでしょうか？

https://github.com/Yuina1012/quelcode-cakephp/blob/4d69d9db07591cbe1f3a8b6dcc1d0479dee46cae/.gitignore#L6-L7

- 商品画面の商品詳細情報でテキストに改行が含まれている場合、改行されずに表示されています。せっかくなので改行して表示されるようにしてください。

2020-11-12 11:49 UTC, Yuina1012 commented
甲斐さんレビューありがとうございます。フォルダの階層が複数階層だったため、以上の2行の記述をしないと思い書き足しました。 (参考にしたのはこちらのサイトです。https://quartet-communications.com/info/topics/13642)

承知いたしました！

2020-11-13 01:17 UTC, Yuzunoha requested changes

2020-11-13 01:17 UTC, Yuzunoha commented on html/mycakeapp/src/Model/Table/BiditemsTable.php
> +                'message' => '画像の拡張子が無効です'
商品画像として無効な拡張子のファイル(`test.txt` など)を送ったときに、
ここで設定している `画像の拡張子が無効です` のエラーメッセージが画面に出ないので、出るようにしてください。

ヒント：エラーメッセージはエラー判定が出た後のエンティティの中に保存されるはずです。まずはそちらを確認しましょう。

2020-11-13 01:22 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			$fileExt = $path_parts["extension"];
```suggestion
			$fileExt = $path_parts["extension"] ?? '';
```
現状「dummyjpeg」のようにピリオド.無しのファイルを送るとここのパス解析でワーニングが出るのでこうしましょう

2020-11-16 01:52 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			$fileExt = $path_parts["extension"];
> 現状「dummyjpeg」のようにピリオド.無しのファイルを送るとここのパス解析でワーニングが出るのでこうしましょう

```php
$fileExt = $path_parts["extension"] ?? '';
```
が先祖返りしてしまっているので元に戻しましょう。ファイル名「dummyjpeg」を送るとワーニングが出ます

2020-11-16 01:53 UTC, Yuzunoha commented
> 現状「dummyjpeg」のようにピリオド.無しのファイルを送るとここのパス解析でワーニングが出るのでこうしましょう

```php
$fileExt = $path_parts["extension"] ?? '';
```

が先祖返りで消えてしまっているので元に戻しましょう。ファイル名「dummyjpeg」を送るとワーニングが出ます

2020-11-16 01:54 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/add.ctp
> +<?= $this->Form->end() ?>
侵入禁止マークが出ているので最終行の末尾で1回改行しましょう

2020-11-16 01:55 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/add.ctp
> +	// echo $this->Form->file('image_name');
prの段階で不要なコメントは削除しましょう。

2020-11-17 01:40 UTC, Yuina1012 commented on html/mycakeapp/src/Template/Auction/add.ctp
> +	// echo $this->Form->file('image_name');
祖先帰りという言葉初めて聞きました！勉強になります。
VScodeのfiles.insertFinalNewlineの設置がオフになっておりました。気づけてよかったです。
コメント消し忘れ見落としました！失礼いたしました。

2020-11-17 02:51 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			$fileExt = $path_parts["extension"] ?? ' ' ;
ちょっと教えてください～。

サジェストと異なりnull合体演算子 `??` の第二オペランドを空文字 `''` ではなく半角スペース `' '` にしているのには理由がありますでしょうか。

2020-11-17 05:14 UTC, Yuzunoha commented
末尾にインデント

 feature/cakephp-challenge1 (#2)
@Yuina1012Yuina1012 committed 4 hours ago
commit eeda575a311331e7f9fae594bfccb335e3711bf8

これはインデントではなく改行です

2020-11-17 05:16 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/AuctionController.php
> +			$fileExt = $path_parts["extension"] ?? ' ' ;
間違えて改変したとのこと

2020-11-17 05:24 UTC, Yuzunoha commented
```php
$fileExt = $path_parts["extension"] ?? ' ' ;
```
を
```php
$fileExt = $path_parts["extension"] ?? '';
```
にしましょう～

セミコロンの前に半角スペースがあるのもサジェストと違うので、どんなに短くてもタイピングではなくコピペしたほうがよいです！

2020-11-17 06:23 UTC, Yuina1012 commented
コピペします！何度も繰り返し同じ箇所を申し訳ございません。

2020-11-17 08:26 UTC, Yuzunoha commented
2706dbef4b7acbebca89982719c8d0bf27b6415a に$のケアレスミスがあり、画像が送れません。

2020-11-17 10:43 UTC, kai-kou commented
確認しました。動作としては概ね問題ないと思います。

ただ2点気になる点があるので、見直しをお願いします。ほんとあともう少しです！

下記実装ですが、

https://github.com/Yuina1012/quelcode-cakephp/blob/017974b23b291ad7478e49ab16f8f446dc910e31/html/mycakeapp/src/Controller/AuctionController.php#L98-L100

1. コメントに `// id,image_name以外を一旦保存`とありますが、コメント前に`$biditem->image_name`に値をセットしているので、コメントとしてはふさわしくないです。

2. ` $this->Biditems->save($biditem);` で一旦保存していますが、ここでバリデーションエラーなどで保存されなかった場合に、以降の処理も継続して実行されてしまうので、今回は大きな問題にはなっていませんが、あまりよろしくない実装になっています。

不明点があれば講師へ質問をお願いします。
また、修正後にはしっかりと動作確認をしてください！

2020-11-17 11:55 UTC, kai-kou commented
確認しました。
指摘点を修正いただけており、動作確認もOKでした！

2020-11-19 10:10 UTC, merged