Feature/js challenge2
yuinakoizumi/quelcode-cakephp pull request #8
Opened 2021-01-13 13:01 UTC by Yuina1012

オークションサイトの商品詳細画面に残り時間のタイマーを表示させる処理をjavascriptとphpで実装しました。
レビューよろしくお願いします。

2021-01-14 00:46 UTC, Yuzunoha commented
https://www.notion.so/8adc1536dc7a49488f6a5c203af9e2fc

2021-01-14 01:09 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/view.ctp
> +		$dif_time_str = $interval->d * 24 * 60 * 60 + +$interval->h * 60 * 60 + $interval->i * 60 + $interval->s; //秒に変換
右辺はstring型ではなくint型になりますね。変数名を直しましょう

2021-01-14 01:16 UTC, Yuzunoha commented on html/mycakeapp/src/Template/Auction/view.ctp
> +		$dif_time_str = $interval->d * 24 * 60 * 60 + +$interval->h * 60 * 60 + $interval->i * 60 + $interval->s; //秒に変換
```php
+ +$interval->h
```
+の代数演算子が1つ余計ですね

2021-01-14 01:21 UTC, Yuzunoha commented on html/mycakeapp/webroot/js/index.js
> +setInterval(function () {
functionをやめてアロー関数にしましょう。今回はアロー関数を変数に代入するとよさそうです。

2021-01-14 01:21 UTC, Yuzunoha commented on html/mycakeapp/webroot/js/index.js
> +		let dif_hour = dif % 86400;
letで宣言する必要がない変数はconstで宣言しましょう。他の個所も同様。

2021-01-14 01:22 UTC, Yuzunoha commented on html/mycakeapp/webroot/js/index.js
> +		console.log(dif);
console.logは掃除しましょう

2021-01-14 01:23 UTC, Yuzunoha commented
現状カウントダウンタイマーが http://localhost:10380/auction/view/7 などのページを表示してから1秒後に表示されています。

jsを工夫して、ページを表示してから1秒待たずにカウントダウンタイマーの表示が始まるようにしましょう。

2021-01-14 01:48 UTC, Yuina1012 commented
ユズノハさんレビューありがとうございます！
上記のご指摘とページ読み込み後すぐに処理するように修正いたします！

2021-01-14 11:16 UTC, kai-kou commented
確認しました。
指摘事項が対応されていましたので、OKです。承認します！

2021-01-14 11:20 UTC, Yuina1012 commented
かいさんレビューありがとうございます！

2021-01-14 12:57 UTC, Yuzunoha requested changes
`ページを表示してから1秒待たずにカウントダウンタイマーの表示が始まるように` の対応が出来ていないようです><

明日説明するのでマージはお待ちください～

2021-01-15 02:07 UTC, Yuzunoha approved these changes
承認しました！！マージしましょう！！！

2021-01-15 02:10 UTC, Yuina1012 commented
ゆずのはさんありがとうございます！マージします！

2021-01-15 02:10 UTC, merged